--DONE--5C.TIM NHAN VIEN KHONG BAN DUOC HANG TRONG THANG KINH DOANH CUOI CUNG NAM 2014
USE B30
GO
DECLARE @THANGKINHDOANHCUOI INT = 5
SELECT *
FROM B30AccDocSales 
where Quantity=0 and MONTH(DocDate) = @THANGKINHDOANHCUOI
AND YEAR(DocDate)=2014