--DONE--5C.TIM NHAN VIEN KHONG BAN DUOC HANG TRONG THANG KINH DOANH CUOI CUNG NAM 2014
USE B30
GO
DECLARE @THANGKINHDOANHCUOI INT = 1
SELECT *
FROM B30AccDocSales
WHERE Quantity=0 AND MONTH(DocDate) = @THANGKINHDOANHCUOI
    AND YEAR(DocDate)=2014