--HALFDONE--5D.TIM NHAN VIEN BAN HANG CO DOANH SO BAN (HAVE AMOUNT=SELECT(MAX(AMOUNT))) NHIEU NHAT TRONG TUNG THANG CUA NAM 2014
USE B30
GO
WITH TBL
AS
(--CREATE VIRTUAL TABLE HAVE SUMAMOUNT OF ALL EMPLOYEE WITH YEAR = 2014
SELECT DocDate,Employeecode,SUM(Amount) AS SUMAMOUNT
FROM B30AccDocSales
WHERE (YEAR(DocDate)='2014')
--AND (MONTH(DocDate)=2)
GROUP BY DocDate,Employeecode)

SELECT (DocDate),Employeecode,SUM(Amount) AS SUM_AMOUNT_2014
FROM B30AccDocSales
WHERE 
--SUM(Amount) = (SELECT AMOUNT FROM TBL) AND 
((Employeecode IN (SELECT Employeecode FROM TBL))AND YEAR(DocDate)='2014')
GROUP BY DocDate,Employeecode
--IMPORTANT
HAVING (MAX(Amount)=
(SELECT MAX(Amount) FROM TBL WHERE MONTH(DocDate)=1))
ORDER BY DocDate,SUM_AMOUNT_2014