--BAI TAP 2: UPDATE BIEN
--VIET SQL TAO BANG TAM CO FIELD[CODE] VA [VALUE] TINH TOAN THEM [ACCUMULATIVE VALUE] 
--LAY DU LIEU TU [SO] DU LIEU NHU SAU

CREATE TABLE #RESOURE
(
    _CODE NVARCHAR(25),
    _VALUE INT
)
SELECT * FROM #RESOURE

 INSERT INTO #RESOURE
 VALUES
     ('A', 1),
     ('B', 3),
     ('C', 2),
     ('D', 5),
     ('E', 7)

 ;WITH CMT AS(
 SELECT * FROM #RESOURE
 )
 --SELECT * FROM CMT
SELECT _CODE,_VALUE, sum(_VALUE) OVER (ORDER BY _CODE ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)
FROM CMT
ORDER BY _CODE

--SELECT _CODE AS CODE,
--_VALUE AS VALUERESOURE,
--    SUM(_VALUE) OVER (
--    PARTITION BY _VALUE 
--ORDER BY _CODE
--ROWS UNBOUNDED PRECEDING)
--AS ROW_VALUE_AFTERPLUS,
--sum(_VALUE) OVER (PARTITION by _VALUE
-- ORDER BY _CODE
-- RANGE UNBOUNDED PRECEDING) as RangeCumulative
--FROM #RESOURE
--ORDER BY _CODE,_VALUE
-- CREATE TABLE #RESULT(
-- _CODE NVARCHAR(25),
-- _VALUE INT,
-- _ACCUMULATIVE_VALUE INT)