--BAI TAP 3: 
--VIET T-SQL DE THE HIEN GIA TRI KET QUAN NHU BANG BEN DUOI
--TAO CAC BANG TAM #B30ACCDOC(ID,DOCDATE,DOCNO,DESCRIPTION,CUSTOMERCODE) VA
--#B30ACCDOCSALES(ID,ITEMCODE,QUANTITY,AMOUNT),
--#B20CUSTOMER(CODE,NAME),
--B20ITEM(CODE,NAME)



CREATE TABLE #RESULT(
_NO INT NULL,
_CODE NVARCHAR(50),
_DOCDATE DATE,
_DOCNO INT,
_DESCRIPTION NVARCHAR(50),
_QUANTITY INT,
_AMOUNT INT,
_DISCOUNT INT
)