--4-baitap4
--TAO BANG TAM DANH MUC VAT TU #B20ITEM(CODE,NAME,GROUPCODE), VA TON KHO DAU KY #B30OPENSTOCK(ITEMCODE,QUANTITY,WAREHOUSECODE)
USE TBL
--BANG TAM DANH MUC VAT TU
IF OBJECT_ID('Tempdb..#B20ITEM') IS NOT NULL DROP TABLE #B20ITEM
CREATE TABLE #B20ITEM(
CODE NVARCHAR(50),
NAME NVARCHAR(50),
GROUPCODE NVARCHAR(50))

--BANG TON KHO DAU KY
IF OBJECT_ID('Tempdb..#B30OPENSTOCK') IS NOT NULL DROP TABLE #B30OPENSTOCK
CREATE TABLE #B30OPENSTOCK(
ITEMCODE NVARCHAR(50),
QUANTITY INT,
WAREHOUSECODE NVARCHAR(50))

--TABLE RESULT
IF OBJECT_ID('Tempdb..#RESULT') IS NOT NULL DROP TABLE #RESULT
CREATE TABLE #RESULT(
GROUPCODE NVARCHAR(50),
ITEMCODE NVARCHAR(50),
ITEMNAME NVARCHAR(50),
STOCK1 INT,
STOCK2 INT,
STOCK3 INT
)