--BAI TAP 1: -THEM BANG TAM #B20WAREHOUSE(DANH MUC KHO),THEM DU LIEU. 
--VIET T-SQL KIEM TRA MA LONG NHAU NHU AB LONG TRONG ABC,
--MA BC KHONG PHAI LA MA LONG TRONG ABC

USE TBL
GO

CREATE TABLE #B20Warehouse(
STT INT IDENTITY(1,1) NOT NULL,
WarehouseCode nvarchar(50)
)

INSERT INTO #B20Warehouse(WarehouseCode)
VALUES ('A'),('B'),('C'),('D')
SELECT * FROM #B20Warehouse