--BAI TAP 3: 
--VIET T-SQL DE THE HIEN GIA TRI KET QUAN NHU BANG BEN DUOI
--TAO CAC BANG TAM 
--#B30ACCDOC(ID,DOCDATE,DOCNO,DESCRIPTION,CUSTOMERCODE) VA
--#B30ACCDOCSALES(ID,ITEMCODE,QUANTITY,AMOUNT),
--#B20CUSTOMER(CODE,NAME),
--#B20ITEM(CODE,NAME)
USE TBL

IF OBJECT_ID('Tempdb..#B30ACCDOC') IS NOT NULL DROP TABLE #B30ACCDOC
CREATE TABLE #B30ACCDOC(
	ID INT IDENTITY(1,1),
	DOCDATE DATE,
	DOCNO INT,
	DESCIPTTION NVARCHAR(MAX),
	CUSTOMERCODE NVARCHAR(30)
)
INSERT INTO #B30ACCDOC
SELECT 
'2010-01-01',001,'BAN HANG 01','AA'
UNION ALL
SELECT 
'2010-01-02',002,'BAN HANG 02','AAB'
UNION ALL
SELECT 
'2010-03-01',003,'BAN HANG 03','AC'
UNION ALL 
SELECT
'2010-03-02',004,'BAN HANG 04','AD'

SELECT * FROM #B30ACCDOC

IF OBJECT_ID('Tempdb..#B30ACCDOCSALES') IS NOT NULL DROP TABLE #B30ACCDOCSALES
CREATE TABLE #B30ACCDOCSALES(
	ID INT IDENTITY(1,1),
	ITEMCODE NVARCHAR(30),
	QUANTITY NUMERIC,
	AMOUNT NUMERIC
)

INSERT INTO #B30ACCDOCSALES
SELECT 
'HD',10,10000000
UNION ALL
 SELECT
 'HD',5,5000000
 UNION ALL
 SELECT 
'HD',8,20000000
UNION ALL
 SELECT 
 'HD',5,15000000

 SELECT * FROM #B30ACCDOCSALES



IF OBJECT_ID('Tempdb..#B20CUSTOMER') IS NOT NULL DROP TABLE #B20CUSTOMER
CREATE TABLE #B20CUSTOMER(
	CODE NVARCHAR(30),
	NAME NVARCHAR(30)
)

IF OBJECT_ID('Tempdb..#B20ITEM') IS NOT NULL DROP TABLE #B20ITEM
CREATE TABLE #B20ITEM(
	CODE NVARCHAR(30),
	NAME NVARCHAR(30)
)

IF OBJECT_ID('Tempdb..#result') IS NOT NULL DROP TABLE #RESULT 
CREATE TABLE #RESULT(
_NO INT NULL,
_CODE NVARCHAR(30),
_DOCDATE DATE,
_DOCNO INT,
_DESCRIPTION NVARCHAR(MAX),
_QUANTITY NUMERIC,
_AMOUNT NUMERIC,
_DISCOUNT NUMERIC
)

;WITH CMT AS(
	SELECT #B30ACCDOC.ID,ITEMCODE,DOCDATE,DOCNO,DESCIPTTION,QUANTITY,AMOUNT
	FROM #B30ACCDOC
	JOIN #B30ACCDOCSALES
	ON #B30ACCDOC.ID=#B30ACCDOCSALES.ID
	)
	--INSERT INTO #RESULT
	INSERT INTO #RESULT(_CODE,_DOCDATE,_DOCNO,_DESCRIPTION,_QUANTITY,_AMOUNT)
	SELECT ITEMCODE,DOCDATE,DOCNO,DESCIPTTION,QUANTITY,AMOUNT FROM CMT




		UPDATE #RESULT SET _DISCOUNT=ROUND(_AMOUNT*3/100,2) WHERE _AMOUNT<10000000
	
		UPDATE #RESULT SET _DISCOUNT=ROUND(_AMOUNT*5/100,2) WHERE _AMOUNT >= 10000000 AND _AMOUNT< 20000000
	
		UPDATE #RESULT SET _DISCOUNT=ROUND(_AMOUNT*7/100,2) WHERE _AMOUNT>=20000000
	
		SELECT * FROM #RESULT

	--DECLARE @DEL INT =1
	--WHILE(SELECT TOP 1 1 FROM #RESULT) =1
	--BEGIN
	
	
	--DELETE #RESULT
	--WHERE _DOCNO=@DEL
	--END
	;WITH CMT AS(
	SELECT TOP 2 *  FROM #RESULT
	)
	INSERT INTO CMT 
	(_QUANTITY
	,_AMOUNT,
	_DISCOUNT)
	SELECT 
	(SELECT SUM(_QUANTITY) FROM CMT),
	(SELECT SUM(_AMOUNT) FROM CMT),
	(SELECT SUM(_DISCOUNT) FROM CMT)
	