IF OBJECT_ID('Tempdb..#tblResource1') IS NOT NULL DROP TABLE #tblResource1
CREATE TABLE #tblResource1
(
	Id INT Identity(1,1),	
	Class NVARCHAR(16),
	Code NVARCHAR(16),
	Value  NUMERIC(18,2)
)

IF OBJECT_ID('Tempdb..#tblResource2') IS NOT NULL DROP TABLE #tblResource2
CREATE TABLE #tblResource2
(
	Id INT Identity(1,1),	
	Class NVARCHAR(16),
	Value  NUMERIC(18,2)
)

INSERT INTO #tblResource1
SELECT 
'F1',	'A',	100
UNION ALL
SELECT
'F1',	'A',	200
UNION ALL
SELECT
'F1',	'B',	100
UNION ALL
SELECT
'F2',	'C',	220
UNION ALL
SELECT
'F3',	'A',	150
UNION ALL
SELECT
'F2',	'C',	300
UNION ALL
SELECT
'F3',	'D',	120

SELECT * FROM #tblResource1

INSERT INTO #tblResource2
SELECT 
'F1',500
UNION ALL
SELECT
'F2',400
UNION ALL
SELECT
'F3',600

SELECT * FROM #tblResource2
--ORDER BY Class,Code
--SELECT * FROM #tblResource2 ORDER BY Class
SELECT T2.CLASS,
T2.CODE,
T2.VALUE,
SUM(T2.VALUE) OVER (PARTITION BY T2.CLASS) AS _SUM,
T1.Value AS _DISTRIBUTED,
ROUND(T2.VALUE/SUM(T2.VALUE) OVER (PARTITION BY T2.CLASS)*T1.VALUE,2) AS RESULT
FROM
(SELECT Class,Code,SUM(Value) AS VALUE
FROM #tblResource1
GROUP BY Class,Code) T2 LEFT OUTER 
JOIN #tblResource2 T1 ON T1.Class = T2.Class
--ORDER BY Class,Code