--1.Tạo chuỗi “Tk LIKE ‘111%’ OR Tk LIKE ‘112%’ OR Tk LIKE ‘131%’” từ chuỗi cho trước “111,112,131”
go
--CREATE DATABASE TBL
GO
USE TBL

DECLARE @STRING NVARCHAR = '111,112,131'

DECLARE @STRING_INPUT VARCHAR(MAX) ='111,112,131'
DECLARE @RESULT VARCHAR(MAX) = REPLACE( CONCAT(',',@STRING_INPUT,'%'),',','%TK LIKE')

SET @RESULT = REPLACE( SUBSTRING(@RESULT,2,LEN(@RESULT)),'%','%,')
SELECT VALUE FROM string_split(@RESULT,',')