--TAO BANG TU CHUOI "A,B,C" TU BANG DU LIEU SAU:
--GO
--CREATE TABLE tblABC(
--  ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY , 
--  CODE NVARCHAR(50),
--  NAME NVARCHAR(50)
--)

  --INSERT INTO tblABC(CODE,NAME)
  --Values ('A','Anh'),
  --('B','By'),
  --('C','Canada')

  --JOIN ALL THE STRING FROM COLUMNS IN A TABLE
  USE TBL 
  GO
  DROP TABLE IF EXISTS #tblABC
  SELECT * 
  INTO #tblABC
  FROM tblABC

 SELECT * 
  FROM #tblABC

DECLARE @DEL INT =1,@STRING NVARCHAR(50) = ''
WHILE (SELECT TOP 1 1 FROM #tblABC) = 1
BEGIN
SELECT TOP 1 @STRING = @STRING +','+ CODE, @DEL =ID
FROM #tblABC
ORDER BY ID

DELETE #tblABC
WHERE ID=@DEL
END
select SUBSTRING(@STRING,2,LEN(@STRING))

--CACH 2
SELECT STRING_AGG(Code,',')
FROM tblABC
