--TAO TABLE TU CHUOI 'A,B,C"
--CREATE TABLE TBLNEWABC(
-- Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
-- Code NVARCHAR(50) NULL
--)
USE TBL
-- SELECT * FROM TBLNEWABC
-- TRUNCATE TABLE TBLNEWABC
DROP TABLE IF EXISTS #TBLNEWABC
SELECT * 
INTO #TBLNEWABC
FROM TBLNEWABC
-- SELECT * FROM #TBLNEWABC
DECLARE @STRING_INPUT VARCHAR(MAX)
SET @STRING_INPUT = 'A,B,C,D,E,F,G,H,I,K,L,M,N'
SELECT VALUE FROM string_split(@STRING_INPUT,',')

INSERT INTO TBLNEWABC(Code)
SELECT  VALUE FROM string_split(@STRING_INPUT,',')

SELECT* FROM TBLNEWABC

TRUNCATE TABLE TBLNEWABC