--TAO TABLE TU CHUOI 'A,B,C"
USE TBL

-- IF OBJECT_ID('Tempdb..#TBLNEWABC') IS NOT NULL DROP TABLE #TBLNEWABC
-- CREATE TABLE #TBLNEWABC(
-- Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
-- Code NVARCHAR(50) NULL
-- )

-- DECLARE @STRING_INPUT VARCHAR(MAX)
-- SET @STRING_INPUT = 'A,B,C,D,E,F,G,H,I,K,L,M,N'
-- INSERT INTO #TBLNEWABC(Code)
-- SELECT  VALUE FROM string_split(@STRING_INPUT,',')

-- SELECT * FROM #TBLNEWABC
-- SELECT VALUE FROM string_split(@STRING_INPUT,',')

IF OBJECT_ID('Tempdb..#tblNewAbc') IS NOT NULL DROP TABLE #tblNewAbc
CREATE TABLE #tblNewAbc(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Code NVARCHAR(50) NULL
)

DECLARE @_ChuoiInput VARCHAR(MAX)
SET @_ChuoiInput = 'A,B,C,D,E,F,G,H,I,K,L,M,N'
INSERT INTO #tblNewAbc(Code)
SELECT  VALUE FROM string_split(@_ChuoiInput,',')

SELECT * FROM #tblNewAbc