--TAO CHUOI "A,B,C" TU BANG DU LIEU SAU:
--GO
--JOIN ALL THE STRING FROM COLUMNS IN A TABLE
USE TBL 
GO
DROP TABLE IF EXISTS #tblABC
SELECT *
INTO #tblABC

FROM tblABC

SELECT *
FROM #tblABC

DECLARE @_Delete INT =1,@_String NVARCHAR(50) = ''
WHILE (SELECT TOP 1
  1
FROM #tblABC) = 1
BEGIN
  SELECT TOP 1
    @_String = @_String +','+ CODE,
    @_Delete =ID
  FROM #tblABC
  ORDER BY ID
  DELETE #tblABC WHERE ID=@_Delete
END
SELECT @_String

SELECT SUBSTRING(@_String,2,LEN(@_String)) AS CACH1

--CACH 2
SELECT STRING_AGG(Code,',') AS CACH2
FROM tblABC