-- TIM HIEU CAC LOAI CHI MUC
USE B30
-- A.TAO MOI CHI MUC
DROP INDEX 
B30AccDocSales.ChiMuc_Test
CREATE INDEX ChiMuc_Test ON B30AccDocSales(DocDate)


--CAC LOAI INDEX TRONG SQL
--SINGLE COLUMN INDEX TRONG SQL
----CREATE INDEX TEN-CHI-MUC ON TENBANG(TEN_COT)
--UNIQUE INDEX TRONG SQL
----CREATE UNIQUE INDEX TEN-CHI-MUC ON TEN-BANG(TEN_COT)
--COMPOSITE INDEX TRONG SQL
----CREATE INDEX TEN_CHI_MUC ON TEN BANG(COT1,COT2)
--IMPLICT INDEX TRONG SQL( LA CHI MUC NGAM DINH) LA CHI MUC
--DUOC TAO TU DONG BOI DATABASE SERVER KHI MOT DOI TUONG DUOC TAO
----DROP INDEX TEN-CHI-MUN
----ON TENBANG(TEN_COT)
----OR DROP INDEX TEN-BANG TNE_CHI_MUC
-- B. XOA CHI MUC

