--CHO BANG DU LIEU CO MOT SO COT THONG TIN KHAI BAO KIEU DU LIEU VARCHAR(64).
--HAY CHINH CAC COT NAY THANH KIEU NVARCHAR(128)
USE tbl 
GO

-- CREATE TABLE #tbl
-- (
--     Ten VARCHAR(64),
--     Id VARCHAR(64)
-- )
DROP TABLE IF EXISTS #tbl
SELECT *
INTO #tbl
FROM tblABC

SELECT *
FROM #tbl

ALTER TABLE #tbl
ALTER COLUMN Name NVARCHAR(128)

-- ALTER TABLE #tbl
-- ALTER COLUMN Id NVARCHAR(128)

SELECT *
FROM #tbl

-- Select rows from a Table or View '[TableOrViewName]' in schema '[dbo]'
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = '#tbl'