use b30
--TIM CAC VIEW CO SU DUNG COT CUSTOMERCODE

CREATE VIEW V_ToDoList AS
SELECT * FROM B30AccDocSales

SELECT * FROM V_ToDoList

SELECT COLUMN_NAME, DATA_TYPE 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'V_ToDoList'