8.Tạo bảng tất cả thứ của tất cả các ngày trong một tháng từ một ngày cho trước.

	DECLARE @DAYINPUTED DATETIME = GETDATE()
	--SELECT @DAYINPUTED AS CURRENTDAY
	DECLARE @COUNT INT= DAY(@DAYINPUTED)
	--SELECT @COUNT
	DECLARE @_COUNTPLUS INT = DAY(@DAYINPUTED)+1

	WHILE ( 1<@COUNT+1)
BEGIN
DECLARE @DATEBEFOREINPUT DATE = DATEADD(DD,-(@COUNT-1),@DAYINPUTED)
    PRINT  DATENAME(WEEKDAY,@DATEBEFOREINPUT) +' ' +DATENAME(DAY,@DATEBEFOREINPUT) +' '+ DATENAME(MONTH,@DATEBEFOREINPUT)
	SET @COUNT=@COUNT-1
END

	WHILE ( @_COUNTPLUS<=31)
BEGIN
DECLARE @DATEAFTERINPUT DATE = DATEADD(DD,@_COUNTPLUS-20,@DAYINPUTED)
    PRINT  DATENAME(WEEKDAY,@DATEAFTERINPUT) +' '+ DATENAME(DAY,@DATEAFTERINPUT) +' '+  DATENAME(MONTH,@DATEAFTERINPUT) 
    --PRINT @_COUNTPLUS
	SET @_COUNTPLUS=@_COUNTPLUS+1
END



