-- 7.Nhân viên vào làm 13/01/1983, nghỉ việc đến thời hiện tại. 
-- Hãy tính thâm niên nhân viên bao nhiêu ngày, bao nhiêu tháng, bao nhiêu năm.

DECLARE @CURRENTDAY date = GETDATE()

--SELECT @CURRENTDAY AS CURRENTDAY

DECLARE @DAYINPUT date = '01-13-1983';

DECLARE @DAY int = DAY(@DAYINPUT)

DECLARE @MONTH int = MONTH(@DAYINPUT)

DECLARE @YEAR int = YEAR(@DAYINPUT)

DECLARE @NAMLAMVIEC INT = YEAR(@CURRENTDAY) - @YEAR

DECLARE @THANGLAMVIEC INT = @NAMLAMVIEC*12 + MONTH(@CURRENTDAY)-@MONTH

DECLARE @NGAYLAMVIEC INT = 6*4*@THANGLAMVIEC

SELECT @NAMLAMVIEC AS NAMLAMVIEC, @THANGLAMVIEC AS THANGDALAMVIEC, @NGAYLAMVIEC AS NGAYDALAMVIEC

--SELECT @DAYINPUT AS DAYINPUT,
--@DAY AS N'NGAY' ,
--@MONTH AS N'THANG',
--@YEAR AS N'NAM'
