-- -Sử dụng các hàm xử lý chuỗi: LEFT, RIGHT, RTRIM, SUBTRING, REPLACE, REPLICATE, STUFF,
-- CHARINDEX, PATINDEX
-- - Sử dụng các hàm xử lý thời gian: DATE, DATEDIFF, DATAPART, YEAR, MONTH, DAY,
-- FORMATDATETIME
-- - Sử dụng các hàm xử lý số: /, %, ROUND, ISNUMERIC
-- - Chuyển đổi số liệu: CAST, CONVERT, STR
-- - Sử dụng các cách khác nhau (nếu có) cho từng câu bài tập
-- 1. Tìm hiểu các kiểu dữ liệu trong Sql Server