--4B--THEM DU LIEU NGAU NHIEN 50 MAT HANG VOI MA SO NGAU NHIEN THEO QUY TAC: 
--KY TU DAU LA "I" VA 4 KY TU SAU NGAU NHIEN TRONG KHOAN TU "0001" - "9999"
use B30
GO
DECLARE @A INT;
DECLARE @B INT;
  
SET @A = 1
SET @B = 9999

DECLARE @COUNT INT =1;
WHILE @COUNT<=50
BEGIN
INSERT INTO B20Item(ItemCode)
VALUES ('I' + cast( @A + FLOOR(RAND() * (@B + 1 - @A))as nvarchar))
SET @COUNT=@COUNT+1
END

SELECT  ItemCode
FROM B20Item