USE B30
GO

--CREATE TABLE B20Prices(
--ItemCode nvarchar(30),
--EffectiveDate date,
--Amount int
--)

--4A--Xoa du lieu cua bang B20ITEM,B30ACCDOCDETAIL,B20CUSTOMER,B20CUSTOMER
TRUNCATE TABLE B20Item
SELECT * FROM B20Item

TRUNCATE TABLE B30AccDocSales
SELECT * FROM B30AccDocSales

TRUNCATE TABLE B20Customer

TRUNCATE TABLE B20Employee

TRUNCATE TABLE B20Item
go
