--4C--THEM DU LIEU NGAU NHIEN 50 KHACH HANG
--VOI MA SO NGAU NHIEN THEO QUY TAC: KY TU DAU NGAU NHIEN
--TRONG BANG KY TU CHU CAI VA 4 KY TU SAU NGAU NHIEN TRONG KHOANG TU "0001" -"9999"

USE B30
GO



DECLARE @BEGIN_NUMBER_CHAR_ASCII INT=65;
DECLARE @END_NUMBER_CHAR_ASCII INT=90;
--DEC HEX CHAR
--65  41  A
--90 5A  Z

--97 61 a
--122 7A z
DECLARE @A INT;
DECLARE @B INT;
SET @A = 0001
SET @B = 9999

DECLARE @COUNT INT =1;
WHILE @COUNT<=50
BEGIN
INSERT INTO B20Customer(CustomerCode)
--DONE
--VALUES (CHAR(RAND()*(@END_NUMBER_CHAR_ASCII-@BEGIN_NUMBER_CHAR_ASCII)+@BEGIN_NUMBER_CHAR_ASCII) + cast( @A + FLOOR(RAND() * (@B + 1 - @A))as nvarchar))
VALUES ('A' + CAST(1+FLOOR(RAND()*(10+1-1))AS nvarchar))
SET @COUNT=@COUNT+1
END

SELECT  CustomerCode
FROM B20Customer

--truncate table b20customer