--2.3. TIM MAT HANG NAO BAN CHAY NHAT TRONG 
--KHOANG THOI GIAN TU '01/01/2013' DEN '31/01/2013'
;WITH
    CMT
    AS
    
    (
        SELECT *
        FROM BANHANG
        WHERE NGAY_CT BETWEEN '2013-01-01' AND '2013-01-31'
    )
--SELECT MAX(SO_LUONG) FROM CMT
SELECT CMT.MA_VT, TEN_VL, NGAY_CT, SO_CT, MA_DT, SO_LUONG, TIEN, ''AS _MATHANGBANCHAYNHAT
FROM CMT
    JOIN DMVT
    ON CMT.MA_VT=DMVT.MA_VT
WHERE SO_LUONG=(SELECT MAX(SO_LUONG)
FROM CMT)

SELECT TOP 1 *
FROM BANHANG
WHERE NGAY_CT BETWEEN '20130101' and '20130131'
ORDER BY SO_LUONG DESC